install: true
cache:
  directories:
    - .build/checkouts # SwiftPM
    - .build/repositories # SwiftPM
branches:
  only:
    - master
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swift test
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swiftlint version
        - swiftlint
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swift package generate-xcodeproj
        - xcodebuild -scheme xcodemissing -enableCodeCoverage YES build test -quiet
      after_success:
        - bash <(curl -s https://codecov.io/bash)
